 server {
      listen 80;

      sub_filter 'http://localhost:9090' '${GATEWAY_URL}';
      sub_filter_once off;
      sub_filter_types *;

      location / {
          root /usr/share/nginx/html;
          index index.html;
          try_files $uri $uri/ /index.html;
      }
  }

