spring.application.name=gateway
server.port=9090

# Eureka registry
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Routes — User microservice
spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=lb://USER
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=users
spring.cloud.gateway.routes[1].uri=lb://USER
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

# Routes — Formation microservice
spring.cloud.gateway.routes[2].id=formations
spring.cloud.gateway.routes[2].uri=lb://FORMATION
spring.cloud.gateway.routes[2].predicates[0]=Path=/formations/**

spring.cloud.gateway.routes[3].id=categories
spring.cloud.gateway.routes[3].uri=lb://FORMATION
spring.cloud.gateway.routes[3].predicates[0]=Path=/categories/**

spring.cloud.gateway.routes[4].id=chapitres
spring.cloud.gateway.routes[4].uri=lb://FORMATION
spring.cloud.gateway.routes[4].predicates[0]=Path=/chapitres/**

# CORS for Angular frontend on :4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
